# Generated by Django 5.0.3 on 2024-03-12 08:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('author_img', models.CharField(max_length=50)),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 3, 12, 8, 59, 2, 398415, tzinfo=datetime.timezone.utc))),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
