# Generated by Django 5.0.3 on 2024-03-18 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_img',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 15, 0, 49, 868885, tzinfo=datetime.timezone.utc)),
        ),
    ]
