# Generated by Django 5.0.3 on 2024-03-19 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_author_img_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 12, 55, 56, 654032, tzinfo=datetime.timezone.utc)),
        ),
    ]
